_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.deeplabv3.DeepLabV3
  encoder_name: "resnet34"
  encoder_depth: 5
  encoder_weights: "imagenet"
  decoder_channels: 256
  in_channels: 3
  num_classes: 6
  activation: null
  upsampling: 8
  aux_params: null

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001