_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.deeplabv3plus.DeepLabV3Plus
  encoder_name: "resnet34"
  encoder_depth: 5
  encoder_weights: "imagenet"
  encoder_output_stride: 16
  decoder_channels: 256
  decoder_atrous_rates: [12, 24, 36],
  in_channels: 3
  num_classes: 6
  activation: null
  upsampling: 4
  aux_params: null

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001