_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.farseg.Farseg
  num_classes: 6
  backbone: "resnet18"
  backbone_pretrained: true

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001