_target_: src.models.ae_module_allclasses.AELitModule

net:
  _target_: src.models.components.fcn.FCN
  num_classes: 4
  in_channels: 3
  num_filters: 64

num_classes: 4

criterion:
  _target_: src.loss.cross_entropy_with_aux.CrossEntropyWithAux

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001