_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.fcn.FCN
  encoder_name: "resnet34"
  encoder_depth: 5
  encoder_weights: "imagenet"
  decoder_pyramid_channels: 256
  decoder_segmentation_channels: 128
  decoder_merge_policy: "add"
  decoder_dropout: 0.2
  in_channels: 3
  num_classes: 6
  activation: null
  upsampling: 4
  aux_params: null

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001