_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.lcnet.LCNet
  num_classes: 6
  block_1: 3
  block_2: 7
  C: 32
  P: 0.5

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001