_target_: src.models.ae_module.AELitModule

net:
  _target_: src.models.components.pspnet.PSPNet
  encoder_name: "resnet34"
  encoder_weights: "imagenet"
  encoder_depth: 3
  psp_out_channels: 512
  psp_use_batchnorm: True
  psp_dropout: 0.2
  in_channels: 3
  num_classes: 6
  activation: null
  upsampling: 8
  aux_params: null

num_classes: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001