_target_: src.models.diffusion_module.DiffusionLitModule

model:
  _target_: src.models.components.seg_diff.diffusion_unet.UNetModel
  in_channels: 1
  model_channels: 128
  out_channels: 1
  num_res_blocks: 2
  attention_resolutions: [16,8]
  rrdb_blocks: 10
  num_classes: 6
  channel_mult: [1, 1, 1, 2, 2, 4, 4]
  num_heads: 4
  num_heads_upsample: -1
  use_scale_shift_norm: false

diffusion:
  _target_: src.models.components.seg_diff.gaussian_diffusion.SpacedDiffusion
  steps: 100
  timestep_respacing: ""
  noise_schedule: "linear"
  predict_xstart: false
  sigma_small: false
  learn_sigma: false
  use_kl: false
  rescale_learned_sigmas: true
  rescale_timesteps: true


num_classes: 6


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001