_target_: src.models.ae_module_allclasses.AELitModule

net:
  _target_: src.models.components.unetmobv2.UNetMobV2
  num_classes: 4

num_classes: 4

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 4